#!/bin/bash

set -e

restore_configs

export V1_VERSION=${V1_VERSION}D

$CFGDIR/common/v1-base-config
$CFGDIR/common/cnc-config
$CFGDIR/accessories/A4988
$CFGDIR/accessories/LCD_USB_Card_mini_12864
$CFGDIR/accessories/dual-drivers-on-xy
$CFGDIR/boards/ATmega2560

opt_set X_DRIVER_TYPE "DRV8825"
opt_set Y_DRIVER_TYPE "DRV8825"
opt_set Z_DRIVER_TYPE "DRV8825"
opt_set X2_DRIVER_TYPE "DRV8825"
opt_set Y2_DRIVER_TYPE "DRV8825"

opt_set X_BED_SIZE "600"
opt_set Y_BED_SIZE "1200"

# opt_disable \
#     E0_DRIVER_TYPE

# Normally Closed Endstop Switch CNC Maker Bot NC -> LOW
opt_set X_MIN_ENDSTOP_HIT_STATE "LOW"
opt_set X2_MIN_ENDSTOP_HIT_STATE "LOW"
opt_set Y_MIN_ENDSTOP_HIT_STATE "LOW"
opt_set Y2_MIN_ENDSTOP_HIT_STATE "LOW"

export PLATFORMIO_ENV=mega2560
