#!/bin/bash

set -e

restore_configs

export V1_VERSION=${V1_VERSION}D

$CFGDIR/common/v1-base-config
$CFGDIR/common/cnc-config
$CFGDIR/boards/ATmega2560
$CFGDIR/accessories/A4988
$CFGDIR/accessories/LCD_USB_Card_mini_12864
$CFGDIR/accessories/dual-drivers-on-xy

opt_set X_DRIVER_TYPE "A4988"
opt_set Y_DRIVER_TYPE "A4988"
opt_set Z_DRIVER_TYPE "A4988"
opt_set X2_DRIVER_TYPE  "A4988"
opt_set Y2_DRIVER_TYPE  "A4988"

opt_set X2_CURRENT 900
opt_set Y2_CURRENT 900

opt_disable \
    E0_DRIVER_TYPE

export PLATFORMIO_ENV=mega2560
